[package]
name = "task"
version = "0.1.0"
authors = ["easy <shinbogdan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stackvec = "0.2.1"